apiVersion: usernaut.dev/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: group-sample
spec:
  # TODO(user): Add fields here
