apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: platformadmin-group
spec:
  group_name: platformadmin-group
  members:
  - user1
  - user2
  backends:
  - name: fivetran
    type: fivetran
  